export { default as Contact } from './contact/Contact'
export { default as Intro } from './Intro/Intro'
export { default as Portfolio } from './portfolio/Portfolio'
export { default as Testimonial } from './testimonials/Testimonials'
export { default as Navbar } from './navbar/Navbar'
export { default as Works } from './works/Works'
export { default as Menu } from './menu/Menu'
export { default as Footer } from './footer/Footer'
